sudo: false

env:
  global:
    - APP_ENV = test

services:
  - docker

# Travis can cache content between builds. This speeds up the build process and saves resources.
cache:
  directories:
    # Cache composer packages so "composer install" is faster.
    - $HOME/.composer/cache/files

# Defines all jobs which Travis will run in parallel. For each PHP version we support we will run one job.
jobs:
  # With fast finishing enabled, Travis CI will mark your build as finished as soon as one of two
  # conditions are met: The only remaining jobs are allowed to fail, or a job has already failed. In
  # these cases, the status of the build can already be determined, so there’s no need to wait around
  fast_finish: true

branches:
  # Those branch will not be deleted. We want push to them without a Pull Request, but trigger the CI anyway
  only:
    - main
    - bad_implementation
    - bad_tests
    - integration_infra_medium_domain
    - integration_infra_medium_domain_wiremock
    - integration_infra_medium_domain_no_di
    - integration_infra_sociable
    - mock_secondary_ports_in_behat

before_install:
  - make preinstall

install:
  - make install

script:
  - make test
