openapi: 3.0.3
info:
  title: TDD Demo ForumPHP 2020
  description: |
    See [JMLamodiere/tdd-demo-forumphp2020](https://github.com/JMLamodiere/tdd-demo-forumphp2020/blob/main/README.md) on GitHub.

  version: 1.0.0

# See https://swagger.io/docs/specification/paths-and-operations/
paths:
  /runningsessions/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/RunningSessionId'

    put:
      summary: Register a running session
      tags: [ Running Session ]
      requestBody:
        required: true
        description: Temperature is enriched by a weather provider
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutRunningSession'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RunningSession'

# See https://swagger.io/docs/specification/components/
components:

  # See https://swagger.io/docs/specification/data-models/
  # NB : they appear in the generated doc
  schemas:

    PutRunningSession:
      type: object
      required: [ id, distance, shoes ]
      properties:
        id:
          $ref: '#/components/schemas/RunningSessionId'
        distance:
          type: number
          format: float
          example: 5.5
        shoes:
          type: string
          example: 'Adadis Turbo2'

    RunningSession:
      allOf:
        # Inherit PutRunningSession
        - $ref: '#/components/schemas/PutRunningSession'
      required: [ temperatureCelcius ]
      properties:
        temperatureCelcius:
          type: float
          example: 37.2

    RunningSessionId:
      type: integer
      minimum: 1
      example: 42

# See https://swagger.io/docs/specification/api-host-and-base-path/
servers:
  - url: 'https://localhost:8000'
    description: dev

  # See https://app.swaggerhub.com/help/integrations/api-auto-mocking
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/JMLamodiere/tdd-demo_forum_php_2020/1.0.0
